databases:
  - name: 832401215-calculator-db
    plan: free
    databaseName: calculator
    user: calculator

services:
  - type: web
    name: 832401215-calculator-backend
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 832401215-calculator-db
          property: connectionString
      - key: CORS_ORIGINS
        sync: false
